### PR TITLE
Migrate denoising modules to scilpy 2.0.0 + nf-test.

### PR DESCRIPTION
**Pull request by gagnonanthony**
## Type of improvement

**If submitting a new module or fixing a bug, please use the appropriate template.**

- [ ] Documentation
- [ ] Development tools (e.g. linter, formatter, etc.)
- [ ] Development container
- [x] Global update (please specify)
- [ ] Other (please specify)

## Describe your improvement

Migrate nlmeans and mppca modules to scilpy 2.0.0 + nf-test.

## Checklist before requesting a review

- [x] Ensure the syntax is correct (**EditorConfig** and **Prettier** must pass)
- [x] Run the test suites if your changes affect any module
- [ ] Regenerate the **Poetry** lock file if you have updated the dependencies
- [ ] Ensure the documentation is up-to-date

#79 #114

### CODE REVIEW

**Review by arnaudbore — APPROVED** [review]
A couple of chmod 755 -> 644 what do we want to do with that ?
GTG

**Comment by AlexVCaron** [comment]
I abide toward a more open 755 set of permissions on the files, but are open to change, if anyone has good reasons. I'm not super good with this kind of thing, so maybe 755 poses a security risk ? I don't think so, but I'm not sure.

`755 - owner can read/write/execute, group/others can read/execute`

`644 - owner can read/write, group/others can read only`

From [here](https://www.multacom.com/faq/password_protection/file_permissions.htm#:~:text=755%20%2D%20owner%20can%20read%2Fwrite,group%2Fothers%20can%20read%20only)

**Comment by gagnonanthony** [comment]
Not sure how those permissions were changed 🤔. Due to my limited knowledge on this matter, I have no preference at all!

**Comment by AlexVCaron** [comment]
Yes, revert for now. I'll add a to-do to research this a bit further.

**Comment by gagnonanthony** [comment]
Just to be safe, do you want me to set all files to 755? Or only those that were changed? I tried doing a `chmod -R 755 modules/nf-scil/denoising/` and most files got changed. Just wanna be sure 😆 (I got scared of committing that)

**Comment by AlexVCaron** [comment]
Just fix yours 😅 But now that I know, I'll urge this a bit more

**Review by AlexVCaron — APPROVED** [review]

**Pull request merged**
