### PR TITLE
[Module] ihMT module

### PR DESCRIPTION
**Pull request by karanphil**
## Describe your changes
I added a module for ihMT. Could not test it since I am waiting for scilpy 2.0. @Manonedde 

## Say which test data are used by your module
It uses ihMT.zip.

## Checklist before requesting a review

- Create the tool:
  - [x] Edit `./modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./modules/nf-scil/<category>/<tool>/meta.yml`
- Generate the tests:
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/main.nf`
  - [x] Edit `./tests/modules/nf-scil/<category>/<tool>/nextflow.config`
  - [x] Add test data locally for tests with the fork repository
  - [ ] Generate the test infrastructure and _md5sum_ for all outputs
- Ensure the syntax is correct :
  - [ ] Check indentation abides with the rest of the library (don't hesitate to correct others !)
  - [ ] Lint everything. Ensure your variables have good names.

### CODE REVIEW

**Review by Manonedde — APPROVED** [review]
LGTM!

NB: Are we going to make a module for “classic” MT images? I know there are people at Max who don't use ihMT, but could MT be a “myelin” sub-workflow?

**Comment by karanphil** [comment]
> LGTM!
> 
> NB: Are we going to make a module for “classic” MT images? I know there are people at Max who don't use ihMT, but could MT be a “myelin” sub-workflow?

It would be easy to almost copy paste this ihmt module and do a "mt" module. I plan to do it someday.

**Review by AlexVCaron — CHANGES_REQUESTED** [review]
Two things, then this should be ready :
- Update your container to 2.0.2
- the `comp_maps` output in your tests is always empty. Is it normal ?

**Comment by karanphil** [comment]
> Two things, then this should be ready :
> 
> * Update your container to 2.0.2
> * the `comp_maps` output in your tests is always empty. Is it normal ?

Good point, there was an option missing in the scil script command line.

**Review by AlexVCaron — APPROVED** [review]
🚀

**Pull request merged**
