### PR TITLE
Migrate betcrop modules to scilpy 2.0 + nf-test.

### PR DESCRIPTION
**Pull request by gagnonanthony**
## Type of improvement

**If submitting a new module or fixing a bug, please use the appropriate template.**

- [ ] Documentation
- [ ] Development tools (e.g. linter, formatter, etc.)
- [ ] Development container
- [x] Global update (please specify)
- [ ] Other (please specify)

## Describe your improvement

Migrate modules within betcrop/ to scilpy 2.0.0 and nf-test framework.

## Checklist before requesting a review

- [x] Ensure the syntax is correct (**EditorConfig** and **Prettier** must pass)
- [x] Run the test suites if your changes affect any module
- [ ] Regenerate the **Poetry** lock file if you have updated the dependencies
- [ ] Ensure the documentation is up-to-date

#79 #114

### CODE REVIEW

**Comment by gagnonanthony** [comment]
Great idea @AlexVCaron, let me know when the archives are available and I'll update the tests.

**Comment by AlexVCaron** [comment]
If you are to do that before I merge #113, then rebase on the `test/data` branch, you'll have access to the archives there. I'll wait for Arnaud before merging those files, it's been enough of Topup testing for a lifetime :wink:

**Review by AlexVCaron — CHANGES_REQUESTED** [review]
Not sure if normal, but some of the modules are missing their `meta.yml` file.

**Comment by gagnonanthony** [comment]
I think it is the permission change that we see because on my end the file is still there and not empty 🤔

**Review by arnaudbore — APPROVED** [review]
GTG

**Pull request merged**
